version: '2.4'

services:
  mysql:
    container_name: mysql
    platform: linux/x86_64 # M1チップ対応のため追記
    image: mysql:8.0.23
    volumes:
      - damp-mysql-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
    # restart: always # 自動起動
    env_file:
      - .env
    environment:
    # .envファイルからパスワード情報など取得
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Tokyo'
    # 本番環境では不要
    ports:
      - "3306:3306"
    tty: true
    networks:
      - damp-network


# 欲しかったらコメントアウトする
  # phpmyadmin:
  #   container_name: pma
  #   depends_on:
  #     - mysql
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     PMA_HOST: mysql
  #   # restart: always # 自動起動
  #   ports:
  #     - "8080:80"

  php-apache: # PHP & Apache
    container_name: web
    build: ./docker/php
    environment:
      PHP_EXTENTION_XDEBUG: 1
    volumes:
      - ./htdocs:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/xdebug.log:/var/log/xdebug.log
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    # restart: always # 自動起動
    ports:
      - "80:80"
    depends_on:
      - mysql
    networks:
      - damp-network

# build用コンテナを作ろうと思ったが、うまくいかない。
# 何か起動させる必要があるが、それが思いつかない。
#   nodejs: # scss & js build用コンテナ
#     container_name: nodejs
#     build:
#       context: . # build用のpathを変更
#       dockerfile: ./docker/nodejs/Dockerfile
#     volumes:
#       - .:/app
#       - nmv:/app/node_modules
#     environment:
#       - NODE_ENV=development

volumes:
  damp-mysql-data:
  # nmv:

# 事前に作成する
# sudo docker network create damp-network
networks:
    damp-network:
        external: true